# Generated by Django 3.0.4 on 2020-03-29 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=100)),
                ('nota', models.CharField(blank=True, max_length=250)),
                ('data_evento', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventi',
            },
        ),
        migrations.CreateModel(
            name='TabellaFermate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fermata', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'fermata',
                'verbose_name_plural': 'fermate',
            },
        ),
        migrations.CreateModel(
            name='Iscrizioni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='iscrizione.Eventi')),
                ('id_fermata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fermate', to='iscrizione.TabellaFermate')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'iscrizione',
                'verbose_name_plural': 'iscrizioni',
            },
        ),
    ]
