# Generated by Django 3.0.4 on 2020-03-29 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizione', '0002_eventi_parte_da'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iscrizioni',
            name='id_fermata',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fermate', to='iscrizione.TabellaFermate'),
        ),
    ]
