# Generated by Django 3.0.4 on 2020-04-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizione', '0003_auto_20200329_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscrizioni',
            name='data_nascita',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iscrizioni',
            name='luogo_di_nascita',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
