# Generated by Django 3.0.4 on 2020-04-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizione', '0005_eventi_numero_massimo_iscritti'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnagraficaNominativi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('luogo_di_nascita', models.CharField(blank=True, max_length=50)),
                ('data_nascita', models.DateTimeField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'Nominativo',
                'verbose_name_plural': 'Nominativi',
            },
        ),
    ]
