# Generated by Django 3.0.4 on 2020-04-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizione', '0006_anagraficanominativi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagraficanominativi',
            name='data_nascita',
            field=models.DateField(blank=True, null=True),
        ),
    ]
