# Generated by Django 3.0.4 on 2020-04-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizione', '0007_auto_20200406_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficanominativi',
            name='id_nominativo',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
