# Generated by Django 3.0.4 on 2020-04-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizione', '0008_anagraficanominativi_id_nominativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anagraficanominativi',
            name='id_nominativo',
        ),
    ]
