# Generated by Django 3.0.4 on 2020-05-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizione', '0011_anagraficanominativi'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.FloatField()),
                ('Number_of_processor', models.PositiveIntegerField()),
                ('efficienza', models.FloatField(max_length=50)),
                ('power_dissipation', models.FloatField()),
            ],
        ),
    ]
