# Generated by Django 3.0.4 on 2020-05-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizione', '0012_powerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerdata',
            name='efficienza',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powerdata',
            name='power_dissipation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
